# Generated by Django 3.0.3 on 2020-10-19 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_pst_criador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='pst_comentarios',
        ),
    ]
