# Generated by Django 3.0.3 on 2020-09-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizacao', '0001_initial'),
        ('equipe', '0002_equipe_eqp_criador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('prj_id', models.AutoField(primary_key=True, serialize=False)),
                ('prj_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('prj_data_criado', models.DateTimeField(auto_now=True)),
                ('prj_data_modificado', models.DateTimeField(auto_now_add=True)),
                ('prj_descricao', models.TextField(max_length=600)),
                ('prj_capa', models.ImageField(upload_to=None)),
                ('prj_criador', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organizacao.Organizacao')),
                ('prj_equipe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='equipe.Equipe')),
            ],
        ),
    ]
