# Generated by Django 3.0.3 on 2020-10-19 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0003_auto_20201018_2312'),
        ('projetos', '0002_projeto_prj_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='prj_capa',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='prj_equipe',
        ),
        migrations.RemoveField(
            model_name='projeto',
            name='prj_likes',
        ),
        migrations.AlterField(
            model_name='projeto',
            name='prj_criador',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='organizacao.Organizacao'),
        ),
    ]
