# Generated by Django 3.0.3 on 2020-10-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='usr_avatar',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_capa',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_equipe',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_likes',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_matchs',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_plano',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_post',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usr_projeto',
        ),
    ]
