# Generated by Django 3.0.3 on 2020-09-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('eqp_id', models.AutoField(primary_key=True, serialize=False)),
                ('eqp_data_criado', models.DateTimeField(auto_now=True)),
                ('eqp_data_modificado', models.DateTimeField(auto_now_add=True)),
                ('eqp_avaliacao', models.IntegerField()),
            ],
        ),
    ]
