# Generated by Django 3.0.3 on 2020-09-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        ('usuario', '0001_initial'),
        ('equipe', '0002_equipe_eqp_criador'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='eqp_lider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='eqp_membros',
            field=models.ManyToManyField(related_name='membros', to='usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='equipe',
            name='eqp_projeto',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto'),
        ),
    ]
