# Generated by Django 3.0.3 on 2020-10-19 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipe', '0003_auto_20200915_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipe',
            name='eqp_avaliacao',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='eqp_criador',
        ),
        migrations.RemoveField(
            model_name='equipe',
            name='eqp_projeto',
        ),
    ]
