# Generated by Django 3.0.3 on 2020-09-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('org_id', models.AutoField(primary_key=True, serialize=False)),
                ('org_nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('org_fundacao', models.DateField(verbose_name='Fundação')),
                ('org_cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('org_estado', models.CharField(max_length=2, verbose_name='Estado (UF)')),
                ('org_area', models.CharField(max_length=20, verbose_name='Area de Atuação')),
                ('org_email', models.EmailField(max_length=254)),
                ('org_telefone', models.IntegerField()),
                ('org_senha', models.CharField(max_length=100)),
                ('org_avatar', models.ImageField(height_field=400, upload_to=None, width_field=400)),
                ('org_capa', models.ImageField(upload_to=None)),
                ('org_bio', models.TextField(max_length=240)),
                ('org_equipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='equipe.Equipe')),
            ],
        ),
    ]
