# Generated by Django 3.0.3 on 2020-09-16 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projetos', '0001_initial'),
        ('organizacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizacao',
            name='org_projeto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projetos.Projeto'),
        ),
    ]
