# Generated by Django 3.0.3 on 2020-10-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0002_organizacao_org_projeto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizacao',
            name='org_capa',
        ),
        migrations.RemoveField(
            model_name='organizacao',
            name='org_equipe',
        ),
        migrations.RemoveField(
            model_name='organizacao',
            name='org_projeto',
        ),
        migrations.AlterField(
            model_name='organizacao',
            name='org_telefone',
            field=models.IntegerField(max_length=9),
        ),
    ]
