# Generated by Django 3.0.3 on 2020-10-19 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizacao', '0003_auto_20201018_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizacao',
            name='org_avatar',
            field=models.ImageField(upload_to=None),
        ),
    ]
